name: 1.0.0$(Rev:.r)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    includeNuGetOrg: true

- task: VSBuild@1
  displayName: build
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:PackageOutputPath="$(build.artifactStagingDirectory)" /p:Version=$(build.buildNumber)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: test
    projects: 'test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
  
- task: NuGetCommand@2
  displayName: 'NuGet push private feed'
  inputs:
    command: push
    publishVstsFeed: 'grilli'
